### ISSUE TITLE
[FAQ] Pawn Spectator Gadget 0: Slot param missing

### ISSUE THREAD

**Issue by connorjak** [SimDynamX/SpaceTeamsPro#43]
### Discussed in https://github.com/SimDynamX/SpaceTeamsPro/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **erSuyognp** October 27, 2024</sup>
Hi, I am having this problem where everything loads but nothing moves. I thought it was problem with my code. But even if I try to run a demo that works on tutorial don't work on mine. When sim starts, I always get this error : "Pawn Spectator Gadget 0 : Slot param missing", I tried to follow BP path I can't find any file like Game or Spacecraft_UI (Maybe I am not supposed to see them). But yeah, I can't run my sim. 

![Screenshot 2024-10-27 185149](https://github.com/user-attachments/assets/5f5f1804-1733-41a9-8d9b-c52588745c94)
</div>

This is a change in [Platform Release 0.27.0](https://github.com/SimDynamX/SpaceTeamsPro/releases/tag/v0.27.0); the spectator `Gadgets` parameter requirements have changed and many of the existing sims have not been updated for this.

The `Static: true` gadgets now require a `Slot` param, which can be either `TopLeft`, `TopRight`, `Left`, or `Right`. This replaces older free-form placement on-screen for static gadgets. `Static: false` gadgets can still work the same as before but many of them have been added as dynamically-addable gadgets from the `Gadgets` button in the UI, so it is unnecessary to specify them in an EntityConfig / SimConfig.

Example before tabbed gadgets change:
```json
{
				"#Required": {
					"Name": "Spectator_Apollo17",
					"Type": "Pawn",
					"Systems": [ "ParamWrangler"]
				},
				"#Pawn": {
					"BP_Path": "/Game/SpaceCraft_UI/FlatScreen/UIP2D_Spectator.UIP2D_Spectator_C",
					"Role_Name": "StartAtApollo17",
					"Is_Possessed": false,
					"Username": "(No User)",
					"GraphicsFrame": ["EntityRef", "Moon"],
					"CamProjMatrix": ["doubleM4x4", 1.0, 0.0, 0.0, 0.0, 
						0.0, 1.0, 0.0, 0.0, 
						0.0, 0.0, 1.0, 0.0, 
						0.0, 0.0, 0.0, 1.0],
					"Gadgets": {
						"0": {
							"Name": "Time",
							"Static": true,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCraft_UI/FlatScreen/TimeManagement.TimeManagement'",
							"IconTexture": "Texture2D'/Game/BuilderTools/WidgetImages/MainMenu/MSTV_MMIcon_Simulate.MSTV_MMIcon_Simulate'",
							"StartsVisible": true,
							"AnchorMin": [ "doubleV2", 0.0, 0.0 ],
							"AnchorMax": [ "doubleV2", 0.0, 0.0 ],
							"Alignment": [ "doubleV2", 0.0, 0.0 ],
							"Position": [ "doubleV2", 0.0, 0.0 ]
						},
						"1": {
							"Name": "Camera",
							"Static": true,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCraft_UI/FlatScreen/W_CameraControl.W_CameraControl'",
							"IconTexture": "Texture2D'/Game/SpaceCraft_UI/FlatScreen/CameraIcon_white.CameraIcon_white'",
							"StartsVisible": true,
							"AnchorMin": [ "doubleV2", 1.0, 0.0 ],
							"AnchorMax": [ "doubleV2", 1.0, 0.0 ],
							"Alignment": [ "doubleV2", 1.0, 0.0 ],
							"Position": [ "doubleV2", 0.0, 0.0 ]
						},
						"2": {
							"Name": "Planet Graphics",
							"Static": false,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCRAFT_2_UI/InSim/Gadgets/W_PlanetGraphicsWithMaterials.W_PlanetGraphicsWithMaterials'",
							"IconTexture": "Texture2D'/Game/PlanetaryDevelopement/PlanetBuilder/PlanetWidet/IconsAndImages/SpaceCRAFT_Icons_PlanetBuilder_Surface__2_.SpaceCRAFT_Icons_PlanetBuilder_Surface__2_'",
							"StartsVisible": false
						},
						"3": {
							"Name": "Outliner",
							"Static": false,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCRAFT_2_UI/InSim/Gadgets/W_SimOutliner.W_SimOutliner'",
							"IconTexture": "Texture2D'/Game/SpaceCraft_UI/Icons/delicious-3-256.delicious-3-256'",
							"StartsVisible": false
						},
						"4": {
							"Name": "Entity Properties",
							"Static": false,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCRAFT_2_UI/InSim/Gadgets/W_EntityProperties2.W_EntityProperties2'",
							"IconTexture": "Texture2D'/Game/SpaceCraft_UI/Icons/delicious-3-256.delicious-3-256'",
							"StartsVisible": false
						},
						"5": {
							"Name": "Planet GPS",
							"Static": true,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCRAFT_2_UI/InSim/W_Planet_GPS.W_Planet_GPS'",
							"IconTexture": "Texture2D'/Game/SpaceCraft_UI/Icons/delicious-3-256.delicious-3-256'",
							"StartsVisible": true,
							"AnchorMin": [ "doubleV2", 0.01, 0.85 ],
							"AnchorMax": [ "doubleV2", 1.0, 1.0 ],
							"Alignment": [ "doubleV2", 0.0, 1.0 ],
							"Position": [ "doubleV2", 1.0, 1.0 ]
						}
					}
				},
```

Example after tabbed gadgets change:
```json
{
				"#Required": {
					"Name": "Spectator_EarthOrbit",
					"Type": "Pawn",
					"Systems": [ "ParamWrangler"]
				},
				"#Pawn": {
					"BP_Path": "/Game/SpaceCraft_UI/FlatScreen/UIP2D_Spectator.UIP2D_Spectator_C",
					"Role_Name": "StartInEarthOrbit",
					"Is_Possessed": false,
					"Username": "(No User)",
					"GraphicsFrame": ["EntityRef", "Earth"],
					"CamProjMatrix": ["doubleM4x4", 1.0, 0.0, 0.0, 0.0, 
						0.0, 1.0, 0.0, 0.0, 
						0.0, 0.0, 1.0, 0.0, 
						0.0, 0.0, 0.0, 1.0],
					"Gadgets": {
						"0": {
							"Name": "Time",
							"Static": true,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCraft_UI/FlatScreen/TimeManagement.TimeManagement'",
							"IconTexture": "Texture2D'/Game/BuilderTools/WidgetImages/MainMenu/MSTV_MMIcon_Simulate.MSTV_MMIcon_Simulate'",
							"Slot": "TopLeft"
						},
						"1": {
							"Name": "Camera",
							"Static": true,
							"WidgetClass": "WidgetBlueprint'/Game/SpaceCraft_UI/FlatScreen/W_CameraControl.W_CameraControl'",
							"IconTexture": "Texture2D'/Game/SpaceCraft_UI/FlatScreen/CameraIcon_white.CameraIcon_white'",
							"Slot": "TopRight"
						}
					}
				},
```

**Comment by erSuyognp** [comment]
Thankyou for helping. I have one more issue:
I tried running the starter sim we are provided(without editing anything). All I get to see is these error message and no movement. Isn't it supposed to follow a movement because there are some command given in exampleMM.py
![image](https://github.com/user-attachments/assets/b1378d2e-ec59-4ced-bc3e-7482e7ca35b9)

**Comment by connorjak** [comment]
You can ignore the material and RotateX errors/warnings; those are left over from some last-minute changes to how model import works.

The sim is supposed to start with waiting for 5 seconds then the rover moving to three different waypoints. The rover may have already finished moving; you can scroll down in the log there and see the OnScreenLogMessage messages from the Mission Manager / LTV Entity Behavior

**Comment by erSuyognp** [comment]
I thought the same, I tried to run sim in -2x but nothing was running. There is nothing except the error in the OnScreenLogMessage. Here is the log file if it helps
[Sim_STU2_SAR_Task1.log](https://github.com/user-attachments/files/17536153/Sim_STU2_SAR_Task1.log)
[Sim_STU2_SAR_Task1_PySys_CompetitionBackend.log](https://github.com/user-attachments/files/17536154/Sim_STU2_SAR_Task1_PySys_CompetitionBackend.log)
[Sim_STU2_SAR_Task1_PySys_CompetitionBackend-BACKUP-.log](https://github.com/user-attachments/files/17536155/Sim_STU2_SAR_Task1_PySys_CompetitionBackend-BACKUP-.log)
[Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV1.log](https://github.com/user-attachments/files/17536156/Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV1.log)
[Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV1-BACKUP-.log](https://github.com/user-attachments/files/17536157/Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV1-BACKUP-.log)
[Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV2.log](https://github.com/user-attachments/files/17536158/Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV2.log)
[Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV2-BACKUP-.log](https://github.com/user-attachments/files/17536159/Sim_STU2_SAR_Task1_PySys_EntityBehavior_LTV2-BACKUP-.log)
[Sim_STU2_SAR_Task1-BACKUP-.log](https://github.com/user-attachments/files/17536160/Sim_STU2_SAR_Task1-BACKUP-.log)

**Comment by connorjak** [comment]
Missing the log for the MissionManager python system. Did it not run?

**Comment by connorjak** [comment]
Your sim config still is pointing to the STU_Competition2 folder for the files, but it looks like instead of changing the paths in the sim config to your repo's default folder name, you changed the folder name to match `STU_Competition2`? It might work for now but this could disrupt things later when submitting. 

I'm not sure exactly what the issue was besides something is going wrong when starting the mission manager python system and it doesn't connect to the sim. If you can run this sim through Compute_Server by command line (see How to Start a Sim wiki page), the console / python output from starting / crashing on that python system may show up there, mixed in with the Logger messages.

**Comment by connorjak** [comment]
Moving this to another Discussion
