### ISSUE TITLE
LTV Losing Communication during Task 1

### ISSUE THREAD

**Issue by Olsons74494** [SimDynamX/SpaceTeamsPro#53]
**Describe the bug**
My search algorithm has consistently failed due to losing communication. Task 1/2 say there should be no loss of communications, is there a simple way of turning this off that I have just missed?

**To Reproduce**
1. Send LTV sufficiently far from the base (my experience is 1-2 steps away from finding the crash site)
2. Provide LTV a new move command
3. Error loss of comms

**Expected behavior**
LTV should move to the next location regardless of hascomms status

**Screenshots**
![image](https://github.com/user-attachments/assets/9c359ad2-dd03-4db3-a48f-e5b3afe39e83)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Platform Version 0.27.3

**Additional context**
I have watched the videos and read documentation but have not seen how to make the LTV move regardless of comms status.

**Comment by connorjak** [comment]
Oh we missed that; the antenna heights aren't high enough by default

In the sim config for Task 1, change all
```json
        "LOSHeight": 10.0
```

on the Beacon entities to 

```json
        "LOSHeight": 500.0
```

We'll eventually put out an updated Task1 sim from STU_Lunar_SAR as well but this fix can be used by everyone for now for Task 1 and Task 2.

**Comment by connorjak** [comment]
Has been fixed for you on both Task 1 and 2 when using v1.1.0 of STU_Lunar_SAR starter code.
